### ISSUE TITLE
Incompatible with command `apt show`, make zombie processes and lead to CPU leak

### ISSUE THREAD

**Issue by dmknght** [marlonrichert/zsh-autocomplete#143]
## Environment
*    zsh-autocomplete f75d296`
*    Zsh version: debian/5.8-5
*    Framework: "none"
*    Plugin manager: "none"
*    ~/.zshrc file:
```
# Greeting
echo "Welcome to Parrot OS"

# Prompt
PROMPT="%F{red}┌[%f%F{cyan}%m%f%F{red}]─[%f%F{yellow}%D{%H:%M-%d/%m}%f%F{red}]─[%f%F{magenta}%d%f%F{red}]%f"$'\n'"%F{red}└╼%f%F{green}$USER%f%F{yellow}$%f"
# Export PATH$
export PATH=~/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:$PATH

# alias
alias ls='ls -lh --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
#####################################################
# Auto completion / suggestion
# Mixing zsh-autocomplete and zsh-autosuggestions
# Requires: zsh-autocomplete (custom packaging by Parrot Team)
# Jobs: suggest files / foldername / histsory bellow the prompt
# Requires: zsh-autosuggestions (packaging by Debian Team)
# Jobs: Fish-like suggestion for command history
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh
# Select all suggestion instead of top on result only
zstyle ':autocomplete:tab:*' insert-unambiguous yes
zstyle ':autocomplete:tab:*' widget-style menu-select
#zstyle ':autocomplete:*' max-lines 100%
#zstyle ':completion:*' list-rows-first yes
#zstyle ':completion:*' group-name ''
zstyle ':autocomplete:*' min-input 2
# Set a bash-like history
bindkey $key[Up] up-line-or-history
bindkey $key[Down] down-line-or-history

##################################################
# Fish like syntax highlighting
# Requires "zsh-syntax-highlighting" from apt
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Save type history for completion and easier life
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
```

# Steps:
1. I used `apt show <package name>`. For example `apt show exploitdb`.
2. information of package shows slowly
# Issues:
1. zombie processes leads to cpu leak (check screenshot bellow)
2. `apt` never suggests package name (it worked before)
![image](https://user-images.githubusercontent.com/29118926/101363520-688aa300-3899-11eb-9f45-d8212c218cd0.png)

**Comment by dmknght** [comment]
After `killall zsh` and closed terminal windows, there are 2 open terminals and this is screenshot
![image](https://user-images.githubusercontent.com/29118926/101364149-2a41b380-389a-11eb-93e4-647be3c9c781.png)

**Comment by dmknght** [comment]
Keep continue with other `apt show` test. Somehow the suggestion still suggest pakage after press tab but terminal hangs
![image](https://user-images.githubusercontent.com/29118926/101364325-5826f800-389a-11eb-87d0-30d2b4dea2ef.png)
Use `Ctrl + C` showed `Killed by signal in _alternative after 59s`

**Comment by marlonrichert** [comment]
@dmknght Can you reproduce this with something else than `apt`? I'm on macOS, so I don't have access to `apt`, which makes it impossible for me to reproduce this. If you could give me a test case where you are able to reproduce it with something else, that would help a lot.

**Comment by dmknght** [comment]
> @dmknght Can you reproduce this with something else than `apt`? I'm on macOS, so I don't have access to `apt`, which makes it impossible for me to reproduce this. If you could give me a test case where you are able to reproduce it with something else, that would help a lot.

for now i have no other case. Do you have same trouble with `brew` (i think so because i have never used macOS).

**Comment by marlonrichert** [comment]
I have tried to reproduce it with `brew`, but no such luck.

**Comment by marlonrichert** [comment]
This should fix it. Let me know if it doesn't.

**Comment by dmknght** [comment]
> This should fix it. Let me know if it doesn't.

I've did a quick test. Likely the "slow" after type `apt show` was fixed but i think sub processes are still there. Well i'll test it more and tell you if problem is not fixed
![image](https://user-images.githubusercontent.com/29118926/101385465-be6c4480-38b3-11eb-8484-321565e9aac2.png)

**Comment by dmknght** [comment]
The problem is still happening.
![image](https://user-images.githubusercontent.com/29118926/101636050-a9fa8a00-3a22-11eb-80d1-200dbe663f8a.png)

**Comment by dmknght** [comment]
@marlonrichert can you reopen this issue, please?

**Comment by marlonrichert** [comment]
I pushed in a potential fix. Can you try it?

**Comment by dmknght** [comment]
> I pushed in a potential fix. Can you try it?

I've tested and it is still happening. Well after some check, i think this bug is just #142 with no "Possibly X"

**Comment by marlonrichert** [comment]
Yeah, I think it's the same. Closing this as duplicate. Let's continue the discussion over there.
