### ISSUE TITLE
Cursor position incorrect when "unambiguous" substring is inserted

### ISSUE THREAD

**Issue by ChocolateOverflow** [marlonrichert/zsh-autocomplete#177]
* `zsh-autocomplete` version: 3f938bb7b4e36c05fcae172360c20c9dfa6e7bb5
* Zsh version: zsh-5.8-0-g77d203f
* Framework: none
* Plugin manager: none

```zsh
$ zstyle ':autocomplete:tab:*' insert-unambiguous yes
$ source path/to/zsh-autocomplete.plugin.zsh
```

When `insert-unambiguous` is set and non-alphanumerical characters in the file names suggested, all similar parts are inserted upon the <TAB>.

```
touch qwe-123-rty qwe-456-rty
file q<TAB> -> file qwe--rty
```

In the example above, since `123` and `456` are the only different parts of the file names, only those are excluded from what is inserted.

```zsh
file q<TAB>1<TAB>

# should make
file qwe-
file qwe-123-rty

# but actually makes
file qwe--rty
file qwe--rty1
```

**Comment by marlonrichert** [comment]
@ChocolateOverflow Thanks for reporting. I fixed it, but not exactly as you requested. For the case you present, it will behave as follows:
```zsh
% file q<tab>
% file qwe--rty
           ^ cursor position
% file qwe-1<tab>-rty
% file qwe-123-rty
```

**Comment by ChocolateOverflow** [comment]
I'd the choice to not have the tailing `-rty` and putting my cursor in the middle. I often change my mind and delete words with `ctrl-w` and having something trailing after my cursor would make it annoying to have to deal with the trailing parts that aren't deleted by `ctrl-w` and `ctrl-u`.

**Comment by marlonrichert** [comment]
@ChocolateOverflow If you change your mind, you can always press `^_` to undo. (Depending on your terminal, this can be <kbd>Ctrl</kbd><kbd>-</kbd> or <kbd>Ctrl</kbd><kbd>/</kbd>.)

**Comment by marlonrichert** [comment]
@ChocolateOverflow I'm still trying to decide what to call the setting you want and how it should work exactly, but in the meantime, you can get the desired effect by adding this to your `.zshrc` file:
```zsh
  zstyle ':completion:*:complete::*' matcher-list \
    'l:?|=[[:punct:]] m:{[:lower:][:punct:]}={[:upper:][:punct:]}' \
    'r:|?=** m:{[:lower:]}={[:upper:]}'

```

**Comment by dmknght** [comment]
I'm having same issue for the folder name. This problem isn't there before. I use tab and ctr+tab for menu selection and this bug really messes everything up

**Comment by dmknght** [comment]
I'm not a zsh script coder but i think this line could have logic bug?
https://github.com/marlonrichert/zsh-autocomplete/blob/f3aebd0ccc2dafed0bfe55a929930072ede03a25/widget/.autocomplete.complete-word.completion-widget#L14

**Comment by marlonrichert** [comment]
@ChocolateOverflow @dmknght It should be fixed now. `insert-unambiguous` now behaves as follows:
```zsh
% file q<tab>
% file qwe-
% file qwe-1<tab>
% file qwe-123-rty
```

**Comment by dmknght** [comment]
![image](https://user-images.githubusercontent.com/29118926/108615568-639bb100-73fd-11eb-8efd-df8434d0e2d7.png)
My problem is still there. This time is for folder name. I deleted cache files, removed old plugin and installed new plugin.

**Comment by dmknght** [comment]
@marlonrichert the sceenshot is what happened after i pressed tab. Please guide me more steps to debug this issue :D

**Comment by marlonrichert** [comment]
@dmknght Can you write down step by step what happens?

**Comment by dmknght** [comment]
> @dmknght Can you write down step by step what happens?

Yeah sure
1. I have folder `zsh-autocomplete` at `/tmp/` with other folders
2. `cd /tmp`
3. `cd zs` or any character that suggest name of `zsh-autocomplete`
![image](https://user-images.githubusercontent.com/29118926/108620160-141bac00-7422-11eb-8274-937f92148721.png)
4. Press `Tab` to select `zsh-autocomplete`
5. Bug showed (for both tab and ctrl + tab) 
![image](https://user-images.githubusercontent.com/29118926/108620168-28f83f80-7422-11eb-8322-6fa7a3563005.png)

**Comment by marlonrichert** [comment]
Sorry, but I cannot reproduce that with the latest commit on the `main` branch. Here's what I did:
```zsh
> cd $(mktemp -d)
> HOME=$PWD zsh -f
% source /Users/marlon/git/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% mkdir zsh-autocomplete
```
I then type `zs` and press <kbd>Tab</kbd>. It completes to `zsh-autocomplete`.

Which version are you using?

**Comment by dmknght** [comment]
> Sorry, but I cannot reproduce that with the latest commit on the `main` branch. Here's what I did:
> 
> ```shell
> > cd $(mktemp -d)
> > HOME=$PWD zsh -f
> % source /Users/marlon/git/zsh-autocomplete/zsh-autocomplete.plugin.zsh
> % mkdir zsh-autocomplete
> ```
> 
> I then type `zs` and press Tab. It completes to `zsh-autocomplete`.
> 
> Which version are you using?

I'm using version `21.02.20` and well this is a little weird because on a fresh build of parrot + your plugin, i don't see the bug either. Somehow it is happening on my PC only.

**Comment by dmknght** [comment]
@marlonrichert an other problem i faced today (that is weird because i saw similar problem of adding `/` was removed).
![image](https://user-images.githubusercontent.com/29118926/108832505-8a0b4900-75c3-11eb-934b-cf0e2fa77c01.png)
Error log from `.xsessionerror`
```
xfwm4-Message: 17:41:02.677: Unsupported keyboard modifier '<Super>Tab'
xfwm4-Message: 17:41:02.677: Unsupported keyboard modifier '<Primary><Super>Down'
xfwm4-Message: 17:41:02.677: Unsupported keyboard modifier '<Primary><Super>Left'
xfwm4-Message: 17:41:02.677: Unsupported keyboard modifier '<Primary><Super>Right'
xfwm4-Message: 17:41:02.677: Unsupported keyboard modifier '<Primary><Super>Up'
```
IDK if `XFCE` made this problem but this is very very weird. I'm testing it on VM

**Comment by dmknght** [comment]
And it has no issue on VM for some reasons

**Comment by dmknght** [comment]
I've just found out the problem won't be there if i type at least 5 characters in terminal (PC)

**Comment by marlonrichert** [comment]
@dmknght Have you tried using the latest commit on the `main` branch on your PC? Does the problem occur there?

**Comment by dmknght** [comment]
> @dmknght Have you tried using the latest commit on the main branch on your PC? Does the problem occur there?

Alright this is really weird. I am on the PC, same version of plugin i used, nothing changed and now it doens't have the problem anymore.

**Comment by marlonrichert** [comment]
Sounds like a caching problem to me.

**Comment by dmknght** [comment]
> Sounds like a caching problem to me.

I agree. The only problem is i deleted all cache file and unless i missed any cache file, i t shouldn't happen. Anyhow the problem is fixed, everything is good, the plugin is ready to go :D
