### ISSUE TITLE
.autocomplete.recent-dirs.precmd:zf_mv:56: /home/stefan/.chpwd-recent-dirs: no such file or directory

### ISSUE THREAD

**Issue by StefanLobbenmeier** [marlonrichert/zsh-autocomplete#244]
* `zsh-autocomplete` version: 473d31a9c949a7e449a9b41fcd57b663c14f9216
* Zsh version: zsh-5.8-0-g77d203f
* Framework: Oh My Zsh
* Plugin manager: Oh My Zsh (right?)

```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% 👉YOUR STEPS TO REPRODUCE👈  # Test and document the steps to reproduce the problem.


# Switch the folder
stefan-manjaro% cd ..
chpwd_recent_filehandler:29: no such file or directory: /tmp/tmp.nEeW3kNxDg/.local/share/zsh/chpwd-recent-dirs
stefan-manjaro% 
```

**Comment by StefanLobbenmeier** [comment]
For context: 

I raised an issue some time ago on another pc, where I also had this issue but was not sure where it was caused from. Today I updated the zsh-autocomplete on this PC (stefan-manjaro) and the issue appeared, so I now suspect that this was related to this plugin.

Unfortunately this time git did not tell me what exactly had been updated, but its been some time since I last update the plugin:

```zsh
➜  zsh-autocomplete git:(master) git pull
remote: Enumerating objects: 1705, done.
remote: Counting objects: 100% (455/455), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 1705 (delta 404), reused 425 (delta 384), pack-reused 1250
Receiving objects: 100% (1705/1705), 1.83 MiB | 4.83 MiB/s, done.
Resolving deltas: 100% (1240/1240), completed with 32 local objects.
From https://github.com/marlonrichert/zsh-autocomplete
 * [new branch]      main       -> origin/main
 * [new tag]         21.02.03   -> 21.02.03
 * [new tag]         21.02.04   -> 21.02.04
 * [new tag]         21.02.14   -> 21.02.14
 * [new tag]         21.02.20   -> 21.02.20
 * [new tag]         21.02.25   -> 21.02.25
 * [new tag]         21.03.04   -> 21.03.04
 * [new tag]         21.03.07   -> 21.03.07
 * [new tag]         21.03.12   -> 21.03.12
 * [new tag]         21.03.19   -> 21.03.19
 * [new tag]         21.04.13   -> 21.04.13
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
➜  zsh-autocomplete git:(master) git fetch
➜  zsh-autocomplete git:(master)
```

**Comment by StefanLobbenmeier** [comment]
I just went through a git bisect:

`git bisect start HEAD 6d27f2bae3d7d6cc98e91ccfe4dfbb8141f5afa4`

Somewhere in there the file /home/stefan/.chpwd-recent-dirs  has been created, so the issue did not appear anymore afterwards. For anyone else that might encounter this issue it might help to manually set the file content, in my case it ended up containing that:
```
➜  ~zsh-autocomplete git:(main) cat /home/stefan/.chpwd-recent-dirs
$'/home/stefan/.oh-my-zsh/custom/plugins/zsh-autocomplete'
```

**Comment by marlonrichert** [comment]
I’m reopening this, since I do intend to fix this.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by gex** [comment]
@marlonrichert i still have this issue. just installed zsh-autocomplete, i'm on [a892bfd](https://github.com/marlonrichert/zsh-autocomplete/commit/a892bfdd13446d42aec0eca2d49117dff0aaf3d6). i just switched to zsh on a brand new macbook so there's a chance i made a mistake somewhere but the error message is very similar to the one above or the one in #242.

my `.zshrc`

```
source ~/.tools/zsh-autocomplete/zsh-autocomplete.plugin.zsh

eval "$(starship init zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
```

and i get the following error

```
❯ cd .tools
chpwd_recent_filehandler:29: no such file or directory: /Users/gex/.local/share/zsh/chpwd-recent-dirs
```

there is no `.local` folder in `~`.

**Comment by marlonrichert** [comment]
Whoops! Looks like I did a too greedy find-and-replace.  😅  Fixed.

---

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 💝
