### ISSUE TITLE
Terminal quits when using <S-Tab> to complete in menu-select

### ISSUE THREAD

**Issue by yutkat** [marlonrichert/zsh-autocomplete#274]
* `zsh-autocomplete` version: 1658d38581c57764dd25980c8a36ff095cf686bb
* Zsh version: 5.8.0.2
* Framework: none
* Plugin manager: none

```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% zstyle ':autocomplete:*' widget-style menu-select
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% ls /
<Shift-Tab> to go back to the previous candidate.
And you press <Shift-Tab> again.
Terminal emulator suddenly quits
```

According to my investigation, this problem seems to occur from the commit of fbd093f7c97a64da92020ba5a6c2756ff56e1c9d.

**Comment by tanderson-google** [comment]
I'm also seeing this issue.  It seems to be a crash in zsh.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by yutkat** [comment]
Thank you for the update.
But, I've tried the main branch and it still seems to reproduce.

**Comment by tomKPZ** [comment]
Same here, the issue still reproduces.  Here's a stack trace: https://pastebin.com/TgK4Ajd0

**Comment by marlonrichert** [comment]
OK, yes, I can reproduce it, too. Let me have another look.

**Comment by marlonrichert** [comment]
Looks like a bug in Zsh to me: https://www.zsh.org/mla/workers/2021/msg01162.html

**Comment by yutkat** [comment]
Oh! it's a bug in zsh. I'm surprised.
Indeed, the following steps reproduced the problem in my environment.

> Steps to reproduce:
```bash
zmodload zsh/complist
tst() { compadd bar baz; compstate[insert]=1 }
zle -C tst menu-select tst
bindkey '^I' tst
bindkey -M menuselect '^[[Z' reverse-menu-complete
ba^I^[[Z
```

But why doesn't it reproduce with fbd093f commit?
I want you to revert this commit if possible.

**Comment by marlonrichert** [comment]
Don't worry, I already know how to work around this. I will commit a fix later today. 🙂

**Comment by marlonrichert** [comment]
All right, now it should _really_ be fixed. 🙂

**Comment by yutkat** [comment]
Great work :tada:  It works for me. Thank you, marlonrichert.
