### ISSUE TITLE
Completion not triggering after `e14687b80`

### ISSUE THREAD

**Issue by paw-lu** [marlonrichert/zsh-autocomplete#282]
* `zsh-autocomplete` version: e14687b80428eb1c22069023b5f12a2ef4f55bcb (works) → 85fdb5750d6bddc621df6ba447027c97fadf2bd4 (does not work) → 112b791326007623c7fdb6234d2f9feb74dae538 (does not work)
* Zsh version: zsh-5.7.1-0-g8b89d0d
* Framework: none
* Plugin manager: none

On one of my machines autocompletion does not work at all—there is no output or interaction when pressing <kbd>tab</kbd>. I've narrowed down the last working commit to e14687b80.

```zsh
$ cd ~zsh-autocomplete
$ git switch main       # Make sure you test with the `main` branch.
$ git pull              # Update to the latest commit.
$ cd $(mktemp -d)       # Create a temp dir and enter it.
$ # Restart Zsh without config files or environment variables in this dir:
$ exec env -i HOME=$PWD PS1='%# ' TERM=$TERM zsh -f
% touch file{0..3}.txt  # Create some files to test autocompletion
% cat file <TAB> <TAB>  # Demonstrate stock autocompletion
file0.txt   file1.txt   file2.txt   file3.txt
% # Checkout latest version as of today
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout 112b791326007623c7fdb6234d2f9feb74dae538
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% cat fi <TAB>          # No output or interaction
% exec env -i HOME=$PWD PS1='%# ' TERM=$TERM zsh -f
% # Checkout last working version
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout e14687b
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% cat fi                # Autocomplete works
file
file0.txt  file1.txt  file2.txt  file3.txt
all matches
file0.txt file1.txt file2.txt file3.txt
common substring: file.txt  (press Shift-Tab to insert)
% exec env -i HOME=$PWD PS1='%# ' TERM=$TERM zsh -f
# Checkout first commit after e14687b
# 7041784 is technically the first commit after e14687b, but 85fdb57 fixes some clobber errors
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout 85fdb5750d6bd
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% cat fi <TAB>          # No output or interaction
```

---

As always, thanks for sharing your project!

**Comment by marlonrichert** [comment]
It works fine for me on the latest commit:
```zsh
% cd $(mktemp -d)
exec env -i PS1='%# ' HOME=$PWD TERM=$TERM zsh -f 
% source /Users/marlon/Git/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% git -C ~zsh-autocomplete rev-parse @
112b791326007623c7fdb6234d2f9feb74dae538
% touch file0.txt  file1.txt  file2.txt  file3.txt
% cat
file
file0.txt  file1.txt  file2.txt  file3.txt
Shift-Tab: insert file.txt
```

Have you tried reinstalling?

**Comment by paw-lu** [comment]
> It works fine for me on the latest commit:

Yeah since it's been non-functioning for me for so long, I suspsect there is something more unique to my machine that made it stop working as expected post e14687b80.

> Have you tried reinstalling?

If by reinstalling you mean deleting the repo and recloning—that doesn't seem to help.

```zsh
% # Remove current version
% trash /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete
% rm -rf $_comp_dumpfile $XDG_CACHE_HOME/zsh
% # Clone newest version
% git clone https://github.com/marlonrichert/zsh-autocomplete.git /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/
% exec env -i HOME=$PWD PS1='%# ' TERM=$TERM zsh -f
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% cat fi <TAB>       # No output
% # Checkout latest working version
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout e14687b
% exec env -i HOME=$PWD PS1='%# ' TERM=$TERM zsh -f
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% cat fi             # Works now
file
file0.txt  file1.txt  file2.txt  file3.txt
all matches
file0.txt file1.txt file2.txt file3.txt
common substring: file.txt  (press Shift-Tab to insert)
```

**Comment by marlonrichert** [comment]
> If by reinstalling you mean deleting the repo and recloning—that doesn't seem to help.

Yes, that's what I meant. 

Aha:
```zsh
% cd $(mktemp -d)
exec env -i PS1='%# ' HOME=$PWD TERM=$TERM zsh -f 
% git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 59 (delta 0), reused 29 (delta 0), pack-reused 0
Receiving objects: 100% (59/59), 1.60 MiB | 4.23 MiB/s, done.
% source zsh-autocomplete/zsh-autocomplete.plugin.zsh 
(anon):35: command not found: .autocomplete.__init__
% 
```
I must have something in _my_ environment that's making it work when I don't use a fresh clone. I'll have to investigate.

**Comment by marlonrichert** [comment]
@paw-lu Are you saying that the first bad commit for you is 70417848c6cd0715955ce4cbaf4b9ed779c7402c?

**Comment by paw-lu** [comment]
> @paw-lu Are you saying that the first bad commit for you is 7041784?

Yes, 7041784 is the first bad commit for me. Apologies if that wans't made clear enough.

7041784 also sometimes gives me `.autocomplete.__init__.precmd:31: can't clobber parameter _autocomplete__log_fd containing file descriptor 0` when sourced. So that's why I checked out 85fdb57 in my example—which is a few commits later. 85fdb57 fixes the clobber errors, but does not fix autocomplete for me.

**Comment by marlonrichert** [comment]
> 7041784 also sometimes gives me `.autocomplete.__init__.precmd:31: can't clobber parameter _autocomplete__log_fd containing file descriptor 0` when sourced. 

Thanks! That makes it a lot more clear what I need to fix.

**Comment by marlonrichert** [comment]
Actually, sorry, no, that doesn't help. As you said yourself, that's fixed in 85fdb57.

I wonder if it has something to do with you using zsh-5.7.1-0-g8b89d0d. 🤔

**Comment by marlonrichert** [comment]
@paw-lu Can you go to `${XDG_DATA_HOME:-$HOME/.local/share}/zsh-autocomplete/log` and have a look what is in the newest log files there? Any error messages?

**Comment by paw-lu** [comment]
There are files there, but all empty it seems.

```console
❯ # Count the number of lines in earch file in log/
❯ wc -l ${XDG_DATA_HOME:-$HOME/.local/share}/zsh-autocomplete/log/*
0 /home/pawlu/.local/share/zsh-autocomplete/log/cpoBLrQn2EgS
0 /home/pawlu/.local/share/zsh-autocomplete/log/fAQ8fo0e3XLu
0 /home/pawlu/.local/share/zsh-autocomplete/log/fxNJ8INz5iif
0 /home/pawlu/.local/share/zsh-autocomplete/log/G5sj7Df2h248
0 /home/pawlu/.local/share/zsh-autocomplete/log/OLGzZREugy56
0 /home/pawlu/.local/share/zsh-autocomplete/log/qkzfGkAX2fLY
0 /home/pawlu/.local/share/zsh-autocomplete/log/vhZPB8w8WDgm
0 total
```

**Comment by marlonrichert** [comment]
OK, try this:
```zsh
% functions -T .autocomplete.async.list-choices.completion-widget
% functions -T .autocomplete.async.list-choices.main-complete
```
Then check the logs again.

**Comment by paw-lu** [comment]
Yeah that did it.
To be clear, I used e40c1318a30 for this one, the latest commit at the time of this post.

```zsh
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout e40c1318a30
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% functions -T .autocomplete.async.list-choices.completion-widget
% functions -T .autocomplete.async.list-choices.main-complete
% wc -l ${XDG_DATA_HOME:-$HOME/.local/share}/zsh-autocomplete/log/*
   0 /tmp/tmp.Qv0xgwWRae/.local/share/zsh-autocomplete/log/0Usvvu92x9Ib
  44 /tmp/tmp.Qv0xgwWRae/.local/share/zsh-autocomplete/log/ZayW1zyA4EZr
  44 total
```


<details>
    <summary><code>ZayW1zyA4EZr</code></summary>

```txt
2 .autocomplete.async.list-choices.completion-widget /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/module/.autocomplete.async
341	local -i nmatches=0
342	local message=''
344	local min_input
344	zstyle -s :autocomplete: min-input min_input
	→ 1
345	cmdor min_input=0 
346	local ignored
346	zstyle -s :autocomplete: ignored-input ignored
	→ 1
348	local +h -a comppostfuncs=( .autocomplete.async.list-choices.post )
349	if [[ -n '' ]]
	→ 1
351	elif ((  1 == 1 && 0 < min_input  ))
	→ 1
352	elif cmdor [[ -n '' ]]
	→ 1
354	elif ((  nmatches == 0  ))
355	elif-then if [[ -n '' ]]
	→ 1
360	elif-then else zle -Rc
367	return 2
341	local -i nmatches=0
342	local message=''
344	local min_input
344	zstyle -s :autocomplete: min-input min_input
	→ 1
345	cmdor min_input=0 
346	local ignored
346	zstyle -s :autocomplete: ignored-input ignored
	→ 1
348	local +h -a comppostfuncs=( .autocomplete.async.list-choices.post )
349	if [[ -n '' ]]
	→ 1
351	elif ((  1 == 1 && 0 < min_input  ))
	→ 1
352	elif cmdor [[ -n '' ]]
	→ 1
354	elif ((  nmatches == 0  ))
355	elif-then if [[ -n '' ]]
	→ 1
360	elif-then else zle -Rc
367	return 2
341	local -i nmatches=0
342	local message=''
344	local min_input
344	zstyle -s :autocomplete: min-input min_input
	→ 1
345	cmdor min_input=0 
346	local ignored
346	zstyle -s :autocomplete: ignored-input ignored
	→ 1
348	local +h -a comppostfuncs=( .autocomplete.async.list-choices.post )
349	if [[ -n '' ]]
	→ 1
351	elif ((  1 == 1 && 0 < min_input  ))
	→ 1
352	elif cmdor [[ -n '' ]]
	→ 1
354	elif ((  nmatches == 0  ))
355	elif-then if [[ -n '' ]]
	→ 1
360	elif-then else zle -Rc
367	return 2
```

</details>

**Comment by marlonrichert** [comment]
@paw-lu Can you update to 20a301d and then try this?
```zsh
functions -t .autocomplete.async.pty.completion-widget
```
And then check the logs again.

**Comment by paw-lu** [comment]
Logs seem empty now.

```zsh
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout 20a301d
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% functions -t .autocomplete.async.pty.completion-widget
% # Logs are empty
% wc -l ${XDG_DATA_HOME:-$HOME/.local/share}/zsh-autocomplete/log/*
0 /tmp/tmp.EDQN0qe3gU/.local/share/zsh-autocomplete/log/2021-06-04T10:47:42.482-Ezs.log
% functions -T .autocomplete.async.list-choices.main-complete
% wc -l ${XDG_DATA_HOME:-$HOME/.local/share}/zsh-autocomplete/log/*
0 /tmp/tmp.EDQN0qe3gU/.local/share/zsh-autocomplete/log/2021-06-04T10:47:42.482-Ezs.log
```

**Comment by marlonrichert** [comment]
Can you update to fd801e4ce6e31c2b4e4985a769d8db80da50b098 and try this?
```zsh
functions -t .autocomplete.async.pty .autocomplete.async.pty.zle-widget
```

**Comment by paw-lu** [comment]
Unfortunatley still empty.

```zsh
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout 20a301d
HEAD is now at 20a301d Add finer-grained logging options
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% functions -t .autocomplete.async.pty .autocomplete.async.pty.zle-widget
% wc -l ${XDG_DATA_HOME:-$HOME/.local/share}/zsh-autocomplete/log/*
0 /tmp/tmp.eS5kHx5z8b/.local/share/zsh-autocomplete/log/2021-06-07T13:31:12.101-Eta.log
```

**Comment by marlonrichert** [comment]
What happens if you paste this into the command line?
```zsh
    print $sysparams[pid]
    {
      local REPLY
      zpty _autocomplete__zpty .autocomplete.async.pty '$LBUFFER' '$RBUFFER'
      zpty -w _autocomplete__zpty $'\t'

      local line
      zpty -r _autocomplete__zpty line '*'$'\0'$'\0'
      zpty -r _autocomplete__zpty line '*'$'\0'$'\0'

      # `zselect -t` w/out other args wants an int > 0
      local -i timeout=$(( 100.0 * (min_delay - SECONDS) ))
      (( timeout > 0 )) &&
          zselect -t $timeout
    } always {
      zpty -d _autocomplete__zpty
      (( TRY_BLOCK_INTERRUPT > 0 )) ||
          print -rNC1 - "$SECONDS" "$line"
    }
```

**Comment by paw-lu** [comment]
```zsh
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout 20a301d
Previous HEAD position was e14687b Fix highlighting bug
HEAD is now at 20a301d Add finer-grained logging options
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% print $sysparams[pid]
{
    local REPLY
    zpty _autocomplete__zpty .autocomplete.async.pty '$LBUFFER' '$RBUFFER'
    zpty -w _autocomplete__zpty $'\t'

    local line
    zpty -r _autocomplete__zpty line '*'$'\0'$'\0'
    zpty -r _autocomplete__zpty line '*'$'\0'$'\0'

    # `zselect -t` w/out other args wants an int > 0
    local -i timeout=$(( 100.0 * (min_delay - SECONDS) ))
    (( timeout > 0 )) &&
        zselect -t $timeout
} always {
    zpty -d _autocomplete__zpty
    (( TRY_BLOCK_INTERRUPT > 0 )) ||
        print -rNC1 - "$SECONDS" "$line"
}

1050245
REPLY=''
line=''
zselect: argument expected after -t
zsh: command not found: #
76%
%
```

**Comment by paw-lu** [comment]
Actually, read the message and saw that the comment was causing issues
Removed

```zsh
% print $sysparams[pid]
{
    local REPLY
    zpty _autocomplete__zpty .autocomplete.async.pty '$LBUFFER' '$RBUFFER'
    zpty -w _autocomplete__zpty $'\t'

    local line
    zpty -r _autocomplete__zpty line '*'$'\0'$'\0'
    zpty -r _autocomplete__zpty line '*'$'\0'$'\0'

    local -i timeout=$(( 100.0 * (min_delay - SECONDS) ))
    (( timeout > 0 )) &&
        zselect -t $timeout
} always {
    zpty -d _autocomplete__zpty
    (( TRY_BLOCK_INTERRUPT > 0 )) ||
        print -rNC1 - "$SECONDS" "$line"
}

1050245
REPLY=12
line=''
183%
%
```

**Comment by marlonrichert** [comment]
Well, that looks like it works. I’m kind baffled by this one.

**Comment by marlonrichert** [comment]
> there is no output or interaction when pressing <kbd>tab</kbd>.

Hm, I think I have to attack it from that angle.

**Comment by marlonrichert** [comment]
@paw-lu Can you try the following?
```zsh
functions -t .autocomplete.complete-word.completion-widget
```
And then press <kbd>tab</kbd>.

**Comment by paw-lu** [comment]
```zsh
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout 20a301d
HEAD is now at 20a301d Add finer-grained logging options
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% functions -t .autocomplete.complete-word.completion-widget
% # <TAB>
% +.autocomplete.complete-word.completion-widget:2> autoload -Uz .autocomplete.complete-word.post
+.autocomplete.complete-word.completion-widget:4> local +h curcontext=complete-word:::
+.autocomplete.complete-word.completion-widget:5> local +h -a comppostfuncs=( .autocomplete.complete-word.post )
+.autocomplete.complete-word.completion-widget:6> [[ complete-word == *-select ]]
+.autocomplete.complete-word.completion-widget:7> [[ $'\t' == [Z ]]
+.autocomplete.complete-word.completion-widget:8> zstyle -t :autocomplete:tab: insert-unambiguous
+.autocomplete.complete-word.completion-widget:15> [[ -n '' ]]
+.autocomplete.complete-word.completion-widget:21> return 0
```

**Comment by marlonrichert** [comment]
OK, that should be fixed now. That doesn't explain the other bug, though. 🤔

**Comment by marlonrichert** [comment]
@paw-lu Can you try this?
```zsh
functions -t .autocomplete.async.start .autocomplete.async.pty .autocomplete.async.complete.fd-widget
```
This should produce output both on screen _and_ in the log.

**Comment by paw-lu** [comment]
Running that makes the terminal unusable, it just keeps repeating the long message. Recording the log path and running in a seperate session still shows empty logs 😅.

<details>
    <summary>Terminal output</summary>

```zsh
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout a1ee18e
HEAD is now at a1ee18e Ensure completion widgets always complete
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% # Output this for later since this leaves terminal unresponsive
% echo ${XDG_DATA_HOME:-$HOME/.local/share}/zsh-autocomplete/log/
/tmp/tmp.PGqHR2Oujv/.local/share/zsh-autocomplete/log/
% functions -t .autocomplete.async.start .autocomplete.async.pty .autocomplete.async.complete.fd-widget
% +.autocomplete.async.start:1> setopt clobber localoptions localtraps extendedglob rcquotes NO_banghist NO_listbeep NO_shortloops NO_warncreateglobal
+.autocomplete.async.start:3> local +h -F SECONDS=0
+.autocomplete.async.start:5> .autocomplete.async.stop
+.autocomplete.async.stop:1> .autocomplete.async.kill _autocomplete__async_complete_fd _autocomplete__async_complete_pid
+.autocomplete.async.kill:1> emulate -L zsh
+.autocomplete.async.kill:1> setopt clobber localoptions localtraps extendedglob rcquotes NO_banghist NO_listbeep NO_shortloops NO_warncreateglobal
+.autocomplete.async.kill:3> local -i fd='' pid=''
+.autocomplete.async.kill:4> ((  pid  ))
+.autocomplete.async.kill:9> ((  fd  ))
+.autocomplete.async.kill:13> unset _autocomplete__async_complete_fd _autocomplete__async_complete_pid
+.autocomplete.async.stop:2> .autocomplete.async.kill _autocomplete__async_timeout_fd _autocomplete__async_timeout_pid
+.autocomplete.async.kill:1> emulate -L zsh
+.autocomplete.async.kill:1> setopt clobber localoptions localtraps extendedglob rcquotes NO_banghist NO_listbeep NO_shortloops NO_warncreateglobal
+.autocomplete.async.kill:3> local -i fd='' pid=''
+.autocomplete.async.kill:4> ((  pid  ))
+.autocomplete.async.kill:9> ((  fd  ))
+.autocomplete.async.kill:13> unset _autocomplete__async_timeout_fd _autocomplete__async_timeout_pid
+.autocomplete.async.stop:3> return 0
+.autocomplete.async.start:7> local -F min_delay
+.autocomplete.async.start:7> zstyle -s :autocomplete: min-delay min_delay
+.autocomplete.async.start:8> min_delay=0
+.autocomplete.async.start:31> read -u 17 _autocomplete__async_complete_pid
+.autocomplete.async.start:32> zle -Fw 17 .autocomplete.async.complete.fd-widget
+.autocomplete.async.start:47> read -u 18 _autocomplete__async_timeout_pid
+.autocomplete.async.start:48> zle -Fw 18 .autocomplete.async.timeout.fd-widget
+.autocomplete.async.start:50> [[ -v 'functions[_zsh_autosuggest_highlight_apply]' ]]
+.autocomplete.async.start:55> true
+.autocomplete.async.complete.fd-widget:1> .autocomplete.zle-flags
+.autocomplete.zle-flags:2> emulate -L zsh
+.autocomplete.zle-flags:2> setopt clobber localoptions localtraps extendedglob rcquotes NO_banghist NO_listbeep NO_shortloops NO_warncreateglobal
+.autocomplete.zle-flags:5> [[ -n '' ]]
+.autocomplete.zle-flags:9> case .autocomplete.async.reset-context (*kill*)
+.autocomplete.zle-flags:9> case .autocomplete.async.reset-context (*yank* | bracketed-paste | put-after)
+.autocomplete.zle-flags:9> case .autocomplete.async.reset-context (put-before)
+.autocomplete.zle-flags:9> case .autocomplete.async.reset-context (*)
+.autocomplete.zle-flags:23> return 0
+.autocomplete.async.complete.fd-widget:4> setopt clobber localoptions localtraps extendedglob rcquotes NO_banghist NO_listbeep NO_shortloops NO_warncreateglobal
+.autocomplete.async.complete.fd-widget:5> setopt NO_completeinword
+.autocomplete.async.complete.fd-widget:5> [[ -z '' ]]
+.autocomplete.async.complete.fd-widget:8> .autocomplete.async.kill _autocomplete__async_timeout_fd _autocomplete__async_timeout_pid
+.autocomplete.async.kill:1> emulate -L zsh
+.autocomplete.async.kill:1> setopt clobber localoptions localtraps extendedglob rcquotes NO_banghist NO_listbeep NO_shortloops NO_warncreateglobal
+.autocomplete.async.kill:3> local -i fd=18 pid=1565259
+.autocomplete.async.kill:4> ((  pid  ))
+.autocomplete.async.kill:5> [[ -o MONITOR ]]
+.autocomplete.async.kill:6> ((  pid *= -1  ))
+.autocomplete.async.kill:7> kill -KILL -1565259
+.autocomplete.async.kill:9> ((  fd  ))
+.autocomplete.async.kill:10> zle -F 18
+.autocomplete.async.kill:13> unset _autocomplete__async_timeout_fd _autocomplete__async_timeout_pid
+.autocomplete.async.complete.fd-widget:10> local -F seconds
+.autocomplete.async.complete.fd-widget:11> local -i nmatches
+.autocomplete.async.complete.fd-widget:12> local message rest
+.autocomplete.async.complete.fd-widget:14> [[ '' == (|hup) ]]
+.autocomplete.async.complete.fd-widget:15> IFS=$'\C-@' +.autocomplete.async.complete.fd-widget:15> read -ru 17 seconds nmatches message rest
+.autocomplete.async.complete.fd-widget:17> .autocomplete.async.kill _autocomplete__async_complete_fd _autocomplete__async_complete_pid
+.autocomplete.async.kill:1> emulate -L zsh
+.autocomplete.async.kill:1> setopt clobber localoptions localtraps extendedglob rcquotes NO_banghist NO_listbeep NO_shortloops NO_warncreateglobal
+.autocomplete.async.kill:3> local -i fd=17 pid=1565258
+.autocomplete.async.kill:4> ((  pid  ))
+.autocomplete.async.kill:5> [[ -o MONITOR ]]
+.autocomplete.async.kill:6> ((  pid *= -1  ))
+.autocomplete.async.kill:7> kill -KILL -1565258
+.autocomplete.async.kill:9> ((  fd  ))
+.autocomplete.async.kill:10> zle -F 17
+.autocomplete.async.kill:13> unset _autocomplete__async_complete_fd _autocomplete__async_complete_pid
+.autocomplete.async.complete.fd-widget:20> ((  _autocomplete__async_avg_duration = .1 * seconds + .9 * _autocomplete__async_avg_duration  ))
+.autocomplete.async.complete.fd-widget:24> setopt promptsubst
+.autocomplete.async.complete.fd-widget:25> local +h PS4=$'%(?,,\t-> %?\n)${${_autocomplete__prev:#${(%)_autocomplete__next}}:+${_autocomplete__prev::=${(%)_autocomplete__next}}}%I\t%(1_,%_ ,)'

# 1. .autocomplete.async.complete.fd-widget	/home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/module/.autocomplete.async
342	if zle ._list_choices -w 0 ''

# 2. .autocomplete.async.list-choices.completion-widget	/home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/module/.autocomplete.async
356	local -i nmatches=0
357	local message=''
359	local min_input
359	zstyle -s :autocomplete: min-input min_input
	-> 1
360	cmdor min_input=0
361	local ignored
361	zstyle -s :autocomplete: ignored-input ignored
	-> 1
363	local +h -a comppostfuncs=( .autocomplete.async.list-choices.post )
364	if [[ -n '' ]]
	-> 1
366	elif ((  1 == 1 && 0 < min_input  ))
	-> 1
367	elif cmdor [[ -n '' ]]
	-> 1
369	elif ((  nmatches == 0  ))
370	elif-then if [[ -n '' ]]
	-> 1
375	elif-then else zle -Rc
  382	return 2

# 1. .autocomplete.async.complete.fd-widget	/home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/module/.autocomplete.async
343	then region_highlight=( )
344	then [[ -v 'functions[_zsh_autosuggest_highlight_apply]' ]]
	-> 1
348	then zle -R
352	return 0
# Terminal repeats entire message upon keypress
```

</details>

```zsh
❯ # Using path from above terminal
❯ wc -l /tmp/tmp.PGqHR2Oujv/.local/share/zsh-autocomplete/log/*
0 /tmp/tmp.PGqHR2Oujv/.local/share/zsh-autocomplete/log/2021-06-08T11:28:13.774-nFj.log
```

**Comment by marlonrichert** [comment]
What happens if you do this?
```zsh
print foobar >&$_autocomplete__log_fd
```
Does `foobar` then show up in the log?

**Comment by paw-lu** [comment]
> Does foobar then show up in the log?

yep!

**Comment by marlonrichert** [comment]
If you do `typeset -gH _autocomplete__log_fd` before sourcing `zsh-autocomplete`, does the problem go away?

**Comment by jocastaneda** [comment]
Curious as to what operating system you are on paw-lu? I was seeing something similar not too long ago with autocomplete on a new install on my macOS machine. The main issue on my end was just it not autocompleting, but now does sans the options showing. I'm not using any plugin manager or framework either.
![autocomplete](https://user-images.githubusercontent.com/1500554/121379121-990ad280-c8f8-11eb-818e-b1201abc7d14.gif)

I will say though, thank you for the work you've been doing on this marlonrichet

**Comment by paw-lu** [comment]
@marlonrichert

> If you do typeset -gH _autocomplete__log_fd before sourcing zsh-autocomplete, does the problem go away?

Kinda. Now hitting <kbd>tab</kbd> does something, though not entirely as expeceted. For example when `file1.txt`, `file2.txt`, and `file3.txt` exist. Hitting tab after any command just automatically fills in `file1.txt`—no output or options are presented

```zsh
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout a1ee18e
HEAD is now at a1ee18e Ensure completion widgets always complete
% typeset -gH _autocomplete__log_fd
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% touch file{1..3}.txt
% cat <TAB>
% cat file1.txt
```

Logs still empty after running `functions -t .autocomplete.async.start .autocomplete.async.pty .autocomplete.async.complete.fd-widget`.

**Comment by paw-lu** [comment]
@jocastaneda

> Curious as to what operating system you are on paw-lu?

CentOS Stream release 8

>  I was seeing something similar not too long ago with autocomplete on a new install on my macOS machine.

Luckily for me, this works expected on my macOS machines. The CentOS machine is my first to have some issues.

> I will say though, thank you for the work you've been doing on this marlonrichet

Yeah can't stress this enough. Even if this doesn't end up resolved, the effort and guidance here is really appreciated.

**Comment by marlonrichert** [comment]
@jocastaneda @paw-lu Thank you for the kind words! 🤗

If you use my software on a regular basis, please consider [being a sponsor](https://github.com/sponsors/marlonrichert). 🙂

**Comment by marlonrichert** [comment]
@paw-lu Does it help when you do this after sourcing `zsh-autocomplete`?
```zsh
typeset -gHa _autocomplete__options=(
  localoptions extendedglob rcquotes NO_banghist NO_clobber NO_listbeep
)
```

**Comment by paw-lu** [comment]
> @paw-lu Does it help when you do this after sourcing zsh-autocomplete?

No. Behaviour is the same—you get a very basic completion with no interaction or output shown.

```zsh
% git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout a1ee18e
HEAD is now at a1ee18e Ensure completion widgets always complete
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% typeset -gHa _autocomplete__options=(
  localoptions extendedglob rcquotes NO_banghist NO_clobber NO_listbeep
)
```

Want to correct https://github.com/marlonrichert/zsh-autocomplete/issues/282#issuecomment-857846082

It seems the <kbd>tab</kbd> responce is restored now even without running `typeset -gH _autocomplete__log_fd`. Though as said in that comment there is no output or interaction shown. It just automatically fills in `file1.txt` (in this case).

```zsh
%  git -C /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete checkout a1ee18e
HEAD is now at a1ee18e Ensure completion widgets always complete
% source /home/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% touch file{1..3}.txt
% cat <TAB>
% cat file1.txt
```

**Comment by marlonrichert** [comment]
@paw-lu Can you try reverting commit 85fdb5750d6bddc621df6ba447027c97fadf2bd4 line by line and see which one fixes the problem?

**Comment by paw-lu** [comment]
Offending line marked in https://github.com/marlonrichert/zsh-autocomplete/commit/70417848c6cd0715955ce4cbaf4b9ed779c7402c#r51960674

I'll repeat what's stated there:

> The breaking portion is actually the second statement on the line. It works as expected if you omit the redirection:
> 
> ```diff
> {
> @@ -237,1 +237,1 @@
> -_main_complete
> +.autocomplete.async.list-choices.complete
> }
> ```

**Comment by paw-lu** [comment]
Simply blindly removing all `2>&$_autocomplete__log_fd` from `module/.autocomplete.async` on latest commit (a1ee18e7d640dbf0ca2ae48001d7d35e9e7080cc) fixes it for me.

**Comment by marlonrichert** [comment]
OK, well, that’s not handy. I wonder why that doesn’t work on CentOS?

@paw-lu Can you give me your `$OSTYPE`? Perhaps I can conditionally remove it.

I thought you said, though, that 85fdb57 was the first commit that broke it for you? Those redirects were already present in e14687b and that worked for you. It makes me think that it’s not the redirects themselves that are the problem, but rather the way I create the file descriptor.

**Comment by paw-lu** [comment]
> @paw-lu Can you give me your $OSTYPE? Perhaps I can conditionally remove it.

It's pretty generic.

```zsh
❯ echo $OSTYPE
linux-gnu
```


> I thought you said, though, that 85fdb57 was the first commit that broke it for you?

To be clear, from https://github.com/marlonrichert/zsh-autocomplete/issues/282#issuecomment-854011914

> Yes, 7041784 is the first bad commit for me. Apologies if that wasn't made clear enough.

e14687b is the last working commit, making 7041784 the breaking commit. It also introduces some clobber errors though which are fixed a couple of commits later in 85fdb57, so I didn't want that getting in the way of debugging, and is why I was chosing it initally as our control.


>  Those redirects were already present in e14687b and that worked for you.

No I don't think the specific `2>&$_autocomplete__log_fd` redirects were present in e14687b

```zsh
❯ cd zsh-autocomplete
❯ # Look at last working commit
❯ git checkout e14687b
HEAD is now at e14687b Fix highlighting bug
❯ # Search for offending snippet
❯ grep --recursive '2>&$_autocomplete__log_fd'
❯ # Go to breaking commit
❯ git checkout 7041784
Previous HEAD position was e14687b Fix highlighting bug
HEAD is now at 7041784 Add logging
❯ # Search for offending snippet
❯ grep --recursive '2>&$_autocomplete__log_fd'
module/.autocomplete.async:      .autocomplete.async.list-choices.complete 2>&$_autocomplete__log_fd
module/.autocomplete.async:  if ! zle ._list_choices -w "$nmatches" "${(Q)message}" 2>&$_autocomplete__log_fd; then
```

Didn't even initially notice the `module/.autocomplete.async:  if ! zle ._list_choices -w "$nmatches" "${(Q)message}" 2>&$_autocomplete__log_fd; then` line. That doesn't seem to break it. Just the first one for this commit.

**Comment by marlonrichert** [comment]
It seems that for some reason, redirecting to that fd when inside a pty breaks things for you. No idea why. But perhaps I can add a test inside the pty to check if the fd is writable.

**Comment by marlonrichert** [comment]
@paw-lu Do you think you could put together a minimal, reproducible test case for this that does not use `zsh-autocomplete`? Then I can ask about it on the Zsh mailing list.

**Comment by marlonrichert** [comment]
@paw-lu Please try updating to the latest commit and see if that helps.

**Comment by paw-lu** [comment]
> Please try updating to the latest commit and see if that helps.

Runs perfectly 😄

**Comment by paw-lu** [comment]
> @paw-lu Do you think you could put together a minimal, reproducible test case for this that does not use zsh-autocomplete? Then I can ask about it on the Zsh mailing list.

Yes I'll attempt this!

Would showing that it does not log as expected be sufficient, or do we need to show it blocking a process?

**Comment by marlonrichert** [comment]
> Would showing that it does not log as expected be sufficient, or do we need to show it blocking a process?

I don’t think it matters. Whichever is the simplest way you can show it behaves differently between CentOS & macOS.

Once you’ve compiled your test case, can you send it yourself to [zsh-workers(at)zsh(dot)org](https://zsh.sourceforge.io/Arc/mlist.html)? I’m sure they’ll want to ask for more info. Better that they get it straight from the source. 🙂
