### ISSUE TITLE
zsh-autocomplete overrides fzf configuration

### ISSUE THREAD

**Issue by andreypopp** [marlonrichert/zsh-autocomplete#4]
First of all, thanks for the amazing completion experience with this plugin!

I'm trying this out now and found out it exports `$FZF_*` environment variables which override my customisations to fzf. I'm wondering why is it doing so and if it's needed — maybe it can be scoped to the plugin's usage of fzf somehow?

**Comment by weilbith** [comment]
Same here. Fzf allows to set these options via CLI arguments per command. It would be awesome to keep other applications unaffected which rely on a user configuration. I use fzf for fairly a lot of other stuff, as it is a very useful tool that I can pipe anything into. I would love to still use my own configuration for that. Maybe I should open a PR to help.

**Comment by marlonrichert** [comment]
I cannot scope my changes to the plugin, but what I _can_ do is look if you have the environment variables already set and if so, use yours instead of mine. I will implement this soon.

**Comment by weilbith** [comment]
@marlonrichert btw: awesome plugin. Love it. :grimacing:

**Comment by marlonrichert** [comment]
This one is a bit tricky. I need the environment variables to communicate to `fzf` plugins what I want them to do. So, I cannot exactly scope them. However, what I can do is check if you've already set them and if so, don't override them.

**Comment by marlonrichert** [comment]
@andreypopp @weilbith I updated the code. Can you test if it resolves the issue for you?

**Comment by weilbith** [comment]
Yes, looks pretty good. :+1: 
But my command history keybind still don't work. Can it be related to that? :thinking:

**Comment by marlonrichert** [comment]
Do you get the same behavior as in #13 ?

**Comment by marlonrichert** [comment]
I will close this issue now, as the original problem has been resolved. Please open a new issue for the command history keybind (or comment on #13, if that's the same issue).
