### ISSUE TITLE
crash when press arrow up key 

### ISSUE THREAD

**Issue by GuannanHu** [marlonrichert/zsh-autocomplete#645]
To reproduce, first, input  something that doesn't match anything in current folder , say, `cd../bash; ` or `cd sdfdsfsf;`  or `nvim ssfs;`
then press the arrow up key twice, the zsh crashes with the following message printed in the terminal. 
```free(): corrupted unsorted chunks```
or 
```corrupted double-linked list ```
or 
```malloc(): unaligned tcache chunk detected ```

```Warning: Program '/bin/zsh' crashed.```

Normally the color of the text of the command changes and it won't prompt anything.

I tried this on another machine with the same setup.
Konsole won't crash it is stuck at `loading`, I have to ctrl+c to stop it.

## Environment

```zsh
% typeset -p1 VENDOR OSTYPE ZSH_PATCHLEVEL _autocomplete__funcfiletrace
```

typeset VENDOR=pc
typeset OSTYPE=linux-gnu
typeset ZSH_PATCHLEVEL=zsh-5.9-0-g73d3173
typeset -a _autocomplete__funcfiletrace=(
  /usr/share/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh:4
  /usr/share/zsh/manjaro-zsh-prompt:6
  /usr/share/zsh/manjaro-zsh-prompt:1
  /home/mjan/.zshrc:9
  zsh:0
)

* Terminal emulator: 
Konsole

.zshrc

```
# Use powerline
USE_POWERLINE="true"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  source /usr/share/zsh/manjaro-zsh-prompt
fi
```

**Comment by SirenityK** [comment]
Try to roll-back to 2023-05-24 release for now until it is fixed; I am not finding (for now) that problem in this version.
I am concerned that you posted this 8 days ago and nobody even noticed, rolling-back apparently gets rid of this bug.

**Comment by GittyMac** [comment]
Sadly the previous version doesn't seem to work with zsh 5.9, just leaving a line of command not found errors in any cases of recursive calls.

**Comment by fshuva** [comment]
I have experienced the same issue. I can reproduce this with intermittently with any failed zsh command, like an invalid program name, etc. Using invalid cd commands, like the OP, can reproduce this issue reliably. 

> 
```shell
typeset VENDOR=ubuntu
typeset OSTYPE=linux-gnu
typeset ZSH_PATCHLEVEL=ubuntu/5.8.1-1
typeset -a _autocomplete__funcfiletrace=(
  /home/fshuva/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh:4
  /home/fshuva/.oh-my-zsh/oh-my-zsh.sh:179
  /home/fshuva/.oh-my-zsh/oh-my-zsh.sh:208
  /home/fshuva/.zshrc:122
  zsh:0
)
```
Terminal: GNOME Terminal

<details><summary>.zshrc</summary>
<p>
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

bindkey '^ ' autosuggest-accept

plugins=(git
    tmux
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-autocomplete
)

source $ZSH/oh-my-zsh.sh
autoload -U compinit; compinit

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

</p>
</details>

**Comment by CheatCod** [comment]
I am having the same issue on m2 MacBook pro zsh 5.9 (x86_64-apple-darwin23.0). Pressing up after a command has failed freezes the shell with the cursor blinking and zsh taking 100% of CPU.

Aftering ctrl-c it gives this:

```
zsh(22992,0x1e12f5300) malloc: Incorrect checksum for freed object 0x12a814000: probably modified after being freed.
Corrupt value: 0x600002b3e200
zsh(22992,0x1e12f5300) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by sunny0531** [comment]
The same is happening on my fedora.
Steps:
1. dnf provides chsh
2. Press up arrow
3. Crash
gdb crash log (not sure if I'm using this right)
Program received signal SIGSEGV, Segmentation fault.                           
0x00007fffea576a08 in singledraw ()user                                        
    at /usr/src/debug/zsh-5.9-7.fc38.x86_64/Src/Zle/complist.c:1953            
Downloading source file /usr/src/debug/zsh-5.9-7.fc38.x86_64/Src/Zle/complist.c
1953        clprintm(g, mtab[ml1 * zterm_columns + mc1], mcc1, ml1, lc1,

**Comment by CheatCod** [comment]
It seems like the issue is fixed on zsh 5.9 m2 macbook pro if you revert to commit `3942311`, still hoping for a proper fix though.

**Comment by kud** [comment]
Got the same issue yeah.

**Comment by 0xluc** [comment]
Same here, when I cd into a folder inside my Downloads folder and I press the up key, it crashes:
`20A[30Cfree(): corrupted unsorted chunks`

**Comment by ZA0068** [comment]
I get this crash issue too on both my terminal and my terminator

**Comment by ZA0068** [comment]
Click on the window you want to change the opacity for
╭─free(): corrupted unsorted chunks················░▒▓ ✔   at 16:18:49   ─╮
[1]    32937 IOT instruction (core dumped)  zsh

**Comment by CarolineMorton** [comment]
Same issue here. On a M2 and it causes a crash, with my CPU usages shooting up to 97% with zsh. The fan even came on!

**Comment by julien-blanchon** [comment]
This is pretty annoying :(

**Comment by Luk9091** [comment]
A simple solution that works for me. 
I did comment out lines 61 to 67 in the file `Completions/_autocomplete__history_lines`

```
   60 local -P groups="${(l:$(( 2 * $#words[CURRENT] ))::=0:):-}"
   61 # _comp_colors=( # ERROR
   62 # "=(#b)${numpat}${lbuffer}(${query})${rbuffer}${rbuffer:+[[:blank:]]#}=2=2=0=0=30; 103$groups"
   63 # "=(#b)${numpat}${lbuffer}(${query})*=2=2=0=30;103$groups"
   64 # "=(#b)${numpat}${lbuffer}(*)=2=2=0"
   65 # "=(#b)${numpat}*=0=2"
   66 # ${(M)_comp_colors:#ma=*}
   67 # )
```

**Comment by julien-blanchon** [comment]
Thanks @Luk9091 ! I think the history should be disable for now, this is breaking almost all my installation. Both macOS and Ubuntu

**Comment by joo920131** [comment]
I get similar issue like this where it just gets stuck 😭


https://github.com/marlonrichert/zsh-autocomplete/assets/42609860/2d23ac6a-ebfc-4acf-85f5-dd5fffef0856

**Comment by ingorichter** [comment]
@joo920131 I see the same issue on my M1 machine with zsh 5.9 :-/

**Comment by lockieluke** [comment]
anyone know if rolling back to an older version works?

**Comment by AustinColby** [comment]
> anyone know if rolling back to an older version works?

Yes, I rolled back to the previous release (https://github.com/marlonrichert/zsh-autocomplete/releases/tag/23.05.24), and I no longer have the issue on both Linux and macOS.

**Comment by tsumarios** [comment]
This is annoying. It also happens to Fedora 39.

**Comment by imreallyliam** [comment]
Experiencing this issue on Debian 11 and MacOS (M2, latest OS)

**Comment by 0xl30** [comment]
Same Issue When Click Arrow Key Terminal Crashed...(Some Time)
Arch Linux 6.6.10
zsh 5.9

**Comment by ChloeColman** [comment]
Same here trying to complete non existing paths
Arch Linux 6.7.0-zen3-1-zen
zsh 5.9 (x86_64-pc-linux-gnu)

**Comment by weberam2** [comment]
I put this at the bottom of my .zshrc

`source ~/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh`

which seems to have fixed it for me

**Comment by lukaskretzschmer** [comment]
Finally, I have been having this issue since I updated and the error happens so fast that you can barely see what it says but it basically a free() error, unsupported chunks, double link something and this happens most of the times when using arrow keys on the history.
**IMPORTANT**
If you use tmux the terminal will just hang there when pressing the arrows keys on the history, I thought tmux was the issue, but with a gnome terminal with zsh I could finally see these errors.
And no, I can roll back because of compatibility issues. But I think it might something about freeing an already "freed" pointer. I am not that good at C.

**Comment by lukaskretzschmer** [comment]
> Finally, I have been having this issue since I updated and the error happens so fast that you can barely see what it says but it basically a free() error, unsupported chunks, double link something and this happens most of the times when using arrow keys on the history. **IMPORTANT** If you use tmux the terminal will just hang there when pressing the arrows keys on the history, I thought tmux was the issue, but with a gnome terminal with zsh I could finally see these errors. And no, I can roll back because of compatibility issues. But I think it might something about freeing an already "freed" pointer. I am not that good at C.

It was a hard issue to find on the internet.

**Comment by samscientist** [comment]
I had the same problem, and do not know exactly why, but it seems to be solved when the plugin is installed by 'Znap', the Zsh plugin manager the repo owner recommended to use.

**Comment by 4brunu** [comment]
@marlonrichert could you please create a new tag so that I can install the new version using homebrew and test the new version? thanks

**Comment by joo920131** [comment]
> I just pushed in a new version. Can you try if the problem still occurs?

Thank you @marlonrichert ! I'll have a play around and see if this issue is resolved for me

**Comment by cigarzh** [comment]
> @marlonrichert could you please create a new tag so that I can install the new version using homebrew and test the new version? thanks

You can brew uninstall and install with --HEAD again

**Comment by YiSunny** [comment]
After upgrading to the latest version (24/09/04), the problem on my side is solved.

**Comment by owquresh** [comment]
This issue is still happening for me on latest version downloaded from brew

**Comment by quartzar** [comment]
This is still happening on both my work laptop (Kubuntu 24.04) and my personal desktop PC (Kubuntu 24.10). I am yet to find a fix. It seems to happen consistently when pressing up arrow to re run a `docker exec` command, interestingly.

**Comment by codethought** [comment]
While I'm not seeing a crash I am still seeing the following errors when I start a new shell on macOS (Ubuntu 22.04 has no issue here using HEAD or latest release tag).

```
zsh-syntax-highlighting: unhandled ZLE widget 'menu-search'
zsh-syntax-highlighting: unhandled ZLE widget 'recent-paths'
```

Switching back to an earlier release with `git reset --hard 23.05.24` and everything works as expected... I should know that I'm following the gist at this location and *not* using the brew releases for the referenced plugins.. 

https://gist.github.com/n1snt/454b879b8f0b7995740ae04c5fb5b7df
